spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: pedro
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false